### ISSUE TITLE
Proxy support gone since jersey 2

### ISSUE THREAD

**Issue by clericc** [leanix/leanix-sdk-java#16]
You forgot to reimplement the proxy support when reimplemented the ApiClient to use Jersey 2, but your Documentation was not updated. Please re-add proxy support.

**Comment by dllx** [comment]
Hi!
According to the Jersey 2 docs, the Client by default uses the JDK HttpURLConnection, which is configurable via the standard system properties http.proxyHost and http.proxyPort. Doesn't this work for you?
As we don't use a proxy here we cannot quickly test this.

**Comment by clericc** [comment]
i consistently get a ConnectionTimeout. I read that too, but was not sure if you are using the default connector.

i create the ApiClient like (xtend):
```
System.setProperty("proxySet", "true")
System.setProperty("http.proxyHost", "http://proxyaddress")
System.setProperty("http.proxyPort", "80")
client = new ApiClient => [
  basePath = "https://ourendpoint/api/v1"
  apiKey = "myToken"			
]
api = new ServicesApi(client)
```

**Comment by dllx** [comment]
Hmm, you did set the correct baseUrl, didn't you?
Maybe there is a problem when fetching the OAuth access token from the tokenUrl before the real call, if you don't use Apikey authentication.
You can try setting apiClient.setDebugging(true) to have the client log its activities (via java.util.logging).
Maybe you can find out then where the problem lies.

Please note that there is now an ApiClientBuilder you can use to create and configure an ApiClient.

**Comment by clericc** [comment]
```
INFORMATION: 1 * Sending client request on thread main
1 > GET https://<censored>.leanix.net/<censored>/api/v1/services?relations=true&filter=
1 > Accept: 
1 > Api-Key: <censored>
1 > User-Agent: Swagger-Codegen/1.0.0/java
```

this is the only apprearing debug msg, then after some seconds:
```
Exception in thread "main" javax.ws.rs.ProcessingException: java.net.ConnectException: Connection timed out: connect
at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
...
at net.leanix.api.common.ApiClient.invokeAPI(ApiClient.java:638)
at net.leanix.api.ServicesApi.getServices(ServicesApi.java:3825)
```

using the Builder leads to the same result sadly...i can only imagine that the proxy settings are somehow ignored...will research on jersey 2 proxy settings...

**Comment by clericc** [comment]
on an unrelated note, the sdk seems to use Api-Key instead of the new X-Api-Key.

**Comment by clericc** [comment]
issue found, i have to set https.proxy.

**Comment by dllx** [comment]
Ah, I didn’t notice that, either. Good to hear it works now!
